// The laptop's health check (tools/health.mjs) on fixtures, so it runs anywhere, GitHub's Linux
// runners too: launchers whose program is gone are caught (the OCR program was registered by
// Chocolatey but missing on disk), PATH and the registry are read right, the papers, agents and
// guards checks see what they exist for, and the report reads as one line when all is well.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  findOnPath, parseShimgenHelp, parseScoopShim, parseExecScript, launcherOf, checkProgram, parseLangs, checkTesseractLangs,
  parseRegPath, expandVars, splitPath, deadPathEntries, words, checkPapers, agentLacks, agentHeaderProblems, localImports, sameText, checkGuards,
  parseAdbDevices, headsetInfo, format, MIN_WORDS
} from '../tools/health.mjs';
import { summarize as summarizeRemarks } from '../tools/coderabbit.mjs';
import { hooksProblems, memoryIndexProblems, pluginProblems, PLUGINS_ON, atLeast, newest } from '../tools/health-setup.mjs';

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'health-'));
const put = (rel, text) => { const f = path.join(tmp, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, text); return f; };
const noRun = () => assert.fail('nothing may be run here');

// Chocolatey's shim help, as its shims print it with --shimgen-help
const SHIMGEN = `[shim]:\n=========\nShim Help\n=========\n\nThis is a shim, generated by Chocolatey's ShimGenerator (shimgen).\nThis shim calls a target with the following settings:\n Target: 'C:\\ProgramData\\chocolatey\\lib\\tesseract\\tools\\tesseract.exe'\n Target exists: 'False'\n Working directory: 'C:\\work'\n`;
assert.deepEqual(parseShimgenHelp(SHIMGEN), { target: 'C:\\ProgramData\\chocolatey\\lib\\tesseract\\tools\\tesseract.exe', exists: false });
assert.equal(parseShimgenHelp('tesseract v5.5.3'), null, 'a program that is no shim');
assert.equal(parseScoopShim('path = "C:\\Users\\me\\scoop\\apps\\ffmpeg\\current\\bin\\ffmpeg.exe"\r\n'), 'C:\\Users\\me\\scoop\\apps\\ffmpeg\\current\\bin\\ffmpeg.exe');
assert.equal(parseExecScript('#!/bin/sh\nexec "/c/Program Files/Tesseract-OCR/tesseract.exe" "$@"\n'), 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe', 'Git Bash\'s /c/ is C:\\');
assert.equal(parseExecScript('#!/bin/sh\nbasedir=$(dirname "$0")\n"$basedir/node" "$@"\n'), null, 'a script with no exec line is not followed');

// Windows finds the name with a runnable extension first, then the bare script; elsewhere the bare name
put('a/tool', '#!/bin/sh\nexec "/c/Gone/tool.exe" "$@"\n');
put('a/tool.cmd', '@echo off\n');
put('a/tool.js', 'not runnable by itself\n');
put('b/tool.exe', 'MZ');
const [a, b] = ['a', 'b'].map((d) => path.join(tmp, d));
assert.deepEqual(findOnPath('tool', [a, b], 'win32', '.COM;.EXE;.BAT;.CMD;.JS'), [path.join(a, 'tool.cmd'), path.join(a, 'tool'), path.join(b, 'tool.exe')]);
assert.deepEqual(findOnPath('tool', [a, b], 'linux'), [path.join(a, 'tool')]);
assert.deepEqual(findOnPath('nothing', [a, b], 'win32'), []);

// a launcher: Scoop's .shim beside it, Chocolatey's shimgen marker, a shell script's exec line
put('scoop/ffmpeg.exe', 'MZ');
put('scoop/ffmpeg.shim', 'path = "C:\\nowhere\\ffmpeg.exe"\n');
assert.deepEqual(launcherOf(path.join(tmp, 'scoop/ffmpeg.exe'), noRun), { kind: 'Scoop', target: 'C:\\nowhere\\ffmpeg.exe' });
put('choco/tesseract.exe', 'MZ...generated by shimgen...');
assert.deepEqual(launcherOf(path.join(tmp, 'choco/tesseract.exe'), () => ({ out: SHIMGEN })), { kind: 'Chocolatey', target: 'C:\\ProgramData\\chocolatey\\lib\\tesseract\\tools\\tesseract.exe' });
assert.equal(launcherOf(path.join(tmp, 'b/tool.exe'), noRun), null, 'a plain program is run as it is');
assert.deepEqual(launcherOf(path.join(a, 'tool'), noRun), { kind: 'script', target: 'C:\\Gone\\tool.exe' });

// a registered program gone from the disk is broken, with its fix; nothing found is broken too
const TESS = { name: 'tesseract', args: ['--version'], expect: /^tesseract v?\d\S*/m, fix: 'reinstall: choco install tesseract -y --force (as administrator)' };
const gone = checkProgram(TESS, [path.join(tmp, 'choco')], { platform: 'win32', runIt: (f, args) => (args[0] === '--shimgen-help' ? { out: SHIMGEN } : noRun()) });
assert.equal(gone.level, 'broken');
assert.match(gone.text, /^tesseract missing on disk \(Chocolatey's launcher .+ points at .+tesseract\.exe, which is gone\): reinstall: choco install tesseract -y --force \(as administrator\)$/);
assert.equal(checkProgram({ ...TESS, name: 'nothing' }, [a, b], { platform: 'win32', runIt: noRun }).level, 'broken');
assert.match(checkProgram({ ...TESS, name: 'nothing' }, [a], { platform: 'linux', runIt: noRun }).text, /^nothing not found on this laptop: reinstall/);
// a program that runs but prints no version is broken; this very node is fine
const silent = checkProgram({ ...TESS, name: 'tool' }, [a], { platform: 'linux', runIt: () => ({ out: '\n', error: 'EACCES' }) });
assert.match(silent.text, /^tool does not run \(EACCES\)/);
const node = checkProgram({ name: path.basename(process.execPath, '.exe'), args: ['--version'], expect: /^v\d+\.\d+\S*/m, fix: '-' }, [path.dirname(process.execPath)]);
assert.equal(node.level, 'ok', node.text);
assert.equal(path.resolve(node.real), path.resolve(process.execPath));
// found only in Git for Windows' own folders: runs from Git Bash only, a warning
const outside = checkProgram({ ...TESS, name: 'tool' }, [], { extra: [a], platform: 'linux', runIt: () => ({ out: 'tesseract v5.5.3\n' }) });
assert.equal(outside.level, 'warning');
assert.match(outside.text, /runs only inside Git Bash/);

// tesseract's languages, as --list-langs prints them
const LANGS = 'List of available languages in "C:\\Program Files\\Tesseract-OCR/tessdata/" (3):\neng\nosd\nrus\n';
assert.deepEqual(parseLangs(LANGS), { dir: 'C:\\Program Files\\Tesseract-OCR/tessdata/', langs: ['eng', 'osd', 'rus'] });
assert.equal(checkTesseractLangs('t', () => ({ out: LANGS })).level, 'ok');
assert.match(checkTesseractLangs('t', () => ({ out: LANGS.replace('rus\n', '') })).text, /^tesseract has no rus language data: put rus\.traineddata .+ into C:\\Program Files\\Tesseract-OCR\/tessdata\/$/);

// PATH: the registry's value, its %variables%, quotes and empty entries
const REG = '\r\nHKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\r\n    Path    REG_EXPAND_SZ    %SystemRoot%\\system32;C:\\Python314;;"C:\\Program Files\\nodejs\\"\r\n\r\n';
const value = parseRegPath(REG);
assert.equal(value, '%SystemRoot%\\system32;C:\\Python314;;"C:\\Program Files\\nodejs\\"');
assert.equal(parseRegPath('    Path    REG_SZ    C:\\a;C:\\b'), 'C:\\a;C:\\b');
assert.equal(parseRegPath('ERROR: The system was unable to find the specified registry key or value.'), '');
const entries = splitPath(expandVars(value, { SYSTEMROOT: 'C:\\WINDOWS' }), 'win32');
assert.deepEqual(entries, ['C:\\WINDOWS\\system32', 'C:\\Python314', 'C:\\Program Files\\nodejs\\']);
assert.deepEqual(splitPath('/usr/bin::/bin', 'linux'), ['/usr/bin', '/bin']);
assert.equal(expandVars('%NOPE%\\x', {}), '%NOPE%\\x', 'an unknown variable stays as written');
const there = new Set([path.join(tmp, 'a')]);
const dead = deadPathEntries([{ where: 'the machine PATH', entries: [path.join(tmp, 'a'), path.join(tmp, 'gone')] }, { where: 'your user PATH', entries: [path.join(tmp, 'gone'), path.join(tmp, 'gone2')] }], (e) => there.has(e));
assert.deepEqual(dead.map((d) => [path.basename(d.entry), d.where]), [['gone', 'the machine PATH'], ['gone2', 'your user PATH']], 'a dead folder named twice is reported once, where it is first');

// the papers: every PDF has a text copy of enough words beside it; the backup holds the same files
const lib = path.join(tmp, 'papers'), backup = path.join(tmp, 'backup');
const prose = Array.from({ length: MIN_WORDS }, (_, i) => `word${i}`).join(' ');
for (const [f, t] of [['a.pdf', '%PDF'], ['a.txt', prose], ['b.pdf', '%PDF'], ['b.txt', 'too few words'], ['c.PDF', '%PDF'], ['sub/d.pdf', '%PDF'], ['sub/d.txt', prose], ['notes.txt', 'no pdf']]) put(`papers/${f}`, t);
assert.equal(words(` one\ttwo\nthree `), 3);
let papers = checkPapers(lib, backup);
assert.equal(papers[0].level, 'broken');
assert.match(papers[0].text, /^2 papers without a text copy of 100\+ words beside it \(b\.pdf, c\.PDF\): make it: pdftotext/);
assert.match(papers[1].text, /^no backup of the papers/);
for (const f of ['a.pdf', 'a.txt', 'b.pdf', 'b.txt', 'c.PDF', 'sub/d.pdf', 'old.txt']) put(`backup/${f}`, 'x');
papers = checkPapers(lib, backup);
assert.equal(papers[1].level, 'broken');
assert.match(papers[1].text, /^2 files of the papers library not in the backup \(notes\.txt, sub\/d\.txt\): copy them: robocopy /);
assert.equal(papers[2].level, 'warning');
assert.match(papers[2].text, /holds 1 file the library no longer has \(old\.txt\)/);
const drive = path.parse(backup).root;
papers = checkPapers(lib, backup, (p) => p !== drive && fs.existsSync(p));
assert.equal(papers.at(-1).level, 'warning', 'the backup drive unplugged is a warning, not broken');
assert.match(papers.at(-1).text, /is not plugged in/);
assert.match(checkPapers(path.join(tmp, 'none'), backup)[0].text, /^the papers library .+ is gone/);

// the research agents: the paper tools, the browser and the library named
const AGENT = '---\nname: quick-research\ntools: WebSearch, mcp__Claude_Browser__navigate, mcp__4ff8cb31-8eb4-4720-944b-24fa9d492ec5__search, mcp__plugin_research-desk_reference-lookup-hosted__search_works, mcp__PDF_Tools__read_pdf_content\n---\nPapers first: C:\\Users\\admin\\Documents\\objekt-papers\n';
assert.deepEqual(agentLacks(AGENT), []);
assert.deepEqual(agentLacks(AGENT.replace(/, mcp__PDF_Tools__\w+/, '').replace(/objekt-papers/, 'library')), ['PDF Tools', 'the papers library (objekt-papers) named in its instructions']);
assert.deepEqual(agentLacks(AGENT.replace('mcp__4ff8cb31-8eb4-4720-944b-24fa9d492ec5__search', 'mcp__4ff8cb31-8eb4-4720-944b-24fa9d492ec5__get_thread')), ['the papers search (4ff8cb31 search)']);
assert.deepEqual(agentLacks('---\nname: x\n---\nobjekt-papers\n'), [], 'no tools line: the agent inherits every tool');
assert.deepEqual(agentLacks(AGENT.replace('reference-lookup-hosted__', 'reference-lookup__')), ['the reference lookup (its hosted copy)'], 'the local copy of the lookup is denied: naming it is having none');
// an agent's header must parse as YAML, or Claude Code drops the agent from every session
assert.deepEqual(agentHeaderProblems('---\nname: x\ndescription: one fact, fast\n---\n'), []);
assert.deepEqual(agentHeaderProblems("---\nname: x\ndescription: 'checks each claim: done, checked'\n---\n"), [], 'a quoted value may hold ": "');
assert.deepEqual(agentHeaderProblems('---\nname: x\ndescription: checks each claim: done, checked\n---\n'), ['the description holds an unquoted ": " (put the value in single quotes)']);
assert.deepEqual(agentHeaderProblems('---\nname: x\n---\n'), ['no description']);
for (const f of fs.readdirSync('.claude/agents')) assert.deepEqual(agentHeaderProblems(fs.readFileSync(path.join('.claude/agents', f), 'utf8')), [], `.claude/agents/${f} loads`);

// the setup around the code (tools/health-setup.mjs): read from the laptop at each session start
assert.deepEqual(hooksProblems('tools/hooks', 'C:/x', (f) => /pre-(commit|push)$/.test(f)), [], 'the hooks folder git runs has both hooks');
assert.equal(hooksProblems('C:/main/tools/hooks', 'C:/x', (f) => f.endsWith('pre-commit')).length, 1, 'a hooks folder without pre-push is caught, an absolute setting read as is');
assert.equal(hooksProblems('', 'C:/x').length, 1, 'no hook setting at all is caught');
assert.deepEqual(memoryIndexProblems('- [A](a.md) — x\n', ['a.md']), []);
assert.deepEqual(memoryIndexProblems('- [A](a.md) — x\n', ['a.md', 'b.md']), ['a memory file the index does not name: b.md']);
assert.deepEqual(memoryIndexProblems('- [A](a.md)\n- [C](c.md)\n', ['a.md']), ['the index names a missing c.md']);
assert.deepEqual(pluginProblems(Object.fromEntries(PLUGINS_ON.map((p) => [p, true]))), [], 'the decided plugins pass');
assert.deepEqual(pluginProblems({ ...Object.fromEntries(PLUGINS_ON.map((p) => [p, true])), 'pr-review-toolkit@claude-plugins-official': true, 'supabase@claude-plugins-official': false }),
  ['pr-review-toolkit@claude-plugins-official is on, though not decided'], 'a plugin he did not decide is caught; one switched off is not');
assert.ok(atLeast('2.1.295', '2.1.294') && atLeast('2.1.294', '2.1.294') && !atLeast('2.1.293', '2.1.294') && atLeast('2.2.0', '2.1.294'));
assert.equal(newest(['2.1.293', '2.1.295', '2.1.30', 'tmp']), '2.1.295', 'versions compared as numbers, not as text');
// CodeRabbit's remarks read at session start (tools/coderabbit.mjs): only its open ones; the baseline it
// compares against moves up only when the newest push was read and nothing is open
const thread = (login, isResolved = false, isOutdated = false, p = 'src/a.js') => ({ isResolved, isOutdated, comments: { nodes: [{ author: { login }, path: p }] } });
const prData = (threads, { state = 'SUCCESS', description = 'Review completed', changedFiles = 12 } = {}) => ({ data: { repository: { pullRequests: { nodes: threads === null ? [] : [{
  number: 10, url: 'https://github.com/x/y/pull/10', headRefOid: 'abcdef1234567', changedFiles,
  commits: { nodes: [{ commit: { status: { contexts: [{ context: 'CodeRabbit', state, description }] } } }] }, reviewThreads: { nodes: threads } }] } } } });
const said = (...a) => summarizeRemarks(prData(...a));
assert.match(said([thread('coderabbitai'), thread('coderabbitai', true), thread('coderabbitai', false, true), thread('exxxit-game')]).line, /^CodeRabbit: 1 open remark on .*pull\/10 \(src\/a\.js\)/, 'only its open, current remarks count');
assert.equal(said([thread('coderabbitai')]).advance, null, 'an open remark keeps the baseline where it is');
assert.equal(said([]).advance, 'abcdef1234567', 'the newest push read with nothing open moves the baseline up');
assert.equal(said([], { state: 'PENDING', description: 'Review in progress' }).advance, null, 'a review still running moves nothing');
const skipped = said([], { description: 'Review skipped: 428 files exceed the limit of 300', changedFiles: 428 });
assert.ok(skipped.advance === null && /428 files against its limit of 300/.test(skipped.line), 'a skipped review is said with its reason and moves nothing');
assert.match(summarizeRemarks(prData(null)).line, /no open pull request from room-polish into reviewed/, 'a missing pull request is said, not passed over');
// the project switches off what loads into every session though the work never uses it
const projectSettings = JSON.parse(fs.readFileSync('.claude/settings.json', 'utf8'));
assert.equal(projectSettings.enabledPlugins['privacy-legal@synced'], false, 'privacy-legal is off for the project');
assert.ok(projectSettings.deniedMcpServers.some((s) => s.serverName === 'plugin:research-desk:reference-lookup'), 'the local copy of the reference lookup is denied; the hosted one is kept');
// the guards: Claude Code runs the main folder's copies; a difference in content (not in line ends) is broken
assert.deepEqual(localImports("import fs from 'node:fs';\nimport { a } from './secrets.mjs';\nimport { b, c } from './board.mjs';\n"), ['secrets.mjs', 'board.mjs']);
assert.ok(sameText('a\r\nb\r\n', 'a\nb\n'));
assert.ok(!sameText('a\n', null), 'a file missing on one side differs');
const here = path.join(tmp, 'here'), main = path.join(tmp, 'main');
for (const dir of ['here', 'main']) {
  const crlf = (s) => (dir === 'here' ? s.replaceAll('\n', '\r\n') : s);
  put(`${dir}/tools/claude-guard.mjs`, crlf("import { x } from './helper.mjs';\n"));
  put(`${dir}/tools/helper.mjs`, crlf('export const x = 1;\n'));
  put(`${dir}/tools/hooks/pre-commit`, crlf('npm test\n'));
  put(`${dir}/.claude/settings.json`, crlf('{}\n'));
}
assert.equal(checkGuards(here, main)[0].level, 'ok', 'the same guards, line ends aside');
assert.match(checkGuards(here, main)[0].text, /\(4 files\)/);
assert.match(checkGuards(here, here)[0].text, /^this is the main folder/);
put('main/tools/helper.mjs', 'export const x = 2;\n');
put('main/tools/hooks/pre-push', 'exit 0\n');
const stale = checkGuards(here, main, 'room-polish')[0];
assert.equal(stale.level, 'broken');
assert.match(stale.text, /\(.+\) and 2 differ from this checkout's \(tools\/helper\.mjs, tools\/hooks\/pre-push\): a guard fixed here is not live; merge this branch into room-polish there/);

// the headset is information only
const DEVICES = '* daemon started successfully\nList of devices attached\n2G0YC1ZF8B0123\tdevice\n\n';
assert.deepEqual(parseAdbDevices(DEVICES), [{ serial: '2G0YC1ZF8B0123', state: 'device' }]);
assert.equal(headsetInfo(parseAdbDevices(DEVICES)).text, 'headset connected');
assert.match(headsetInfo(parseAdbDevices('List of devices attached\nX\tunauthorized\n')).text, /accept the USB debugging/);
assert.equal(headsetInfo([]).level, 'info');

// the report: one line when all is well; else the count and one plain line per problem, broken first
const okOnly = [{ level: 'ok', text: 'node: v24' }, { level: 'ok', text: 'git: 2.56' }, { level: 'info', text: 'no headset on the cable' }];
assert.equal(format(okOnly), 'health: ok (3 checks)');
assert.equal(format(okOnly, { all: true }), 'health: ok (3 checks)\nok: node: v24\nok: git: 2.56\ninfo: no headset on the cable');
const mixed = [...okOnly, { level: 'warning', text: 'PATH names a folder that does not exist: C:\\Old' }, { level: 'broken', text: 'tesseract missing on disk: reinstall: choco install tesseract -y --force (as administrator)' }];
assert.equal(format(mixed), 'health: 1 broken, 1 to look at\nbroken: tesseract missing on disk: reinstall: choco install tesseract -y --force (as administrator)\nwarning: PATH names a folder that does not exist: C:\\Old');
assert.equal(format([...okOnly, mixed[3]]), 'health: ok (4 checks), 1 to look at\nwarning: PATH names a folder that does not exist: C:\\Old');

fs.rmSync(tmp, { recursive: true, force: true });
console.log('health tests: ok');
