import { getContext } from './audio.js';

// Experimenter voice from pre-recorded files. Quest Browser has no speech
// synthesis at all, so recorded audio is the only voice that works in a headset.
// Files are generated by tools/make-voice.mjs.
const raw = new Map();      // text -> Promise<ArrayBuffer | null>
const decoded = new Map();  // text -> Promise<AudioBuffer | null>
let current = null;

// lines: [{ text, file }]; file is resolved against baseUrl (the room module URL).
export function loadVoice(lines, baseUrl) {
  for (const { text, file } of lines) {
    raw.set(text, fetch(new URL(file, baseUrl))
      .then(r => (r.ok ? r.arrayBuffer() : null))
      .catch(() => null));
  }
}

// Plays the recording for this exact text, stopping the previous one.
// Silent when there is no recording or audio is not unlocked yet.
export function speak(text) {
  const ctx = getContext();
  if (!ctx || !raw.has(text)) return;
  if (!decoded.has(text)) {
    decoded.set(text, raw.get(text)
      .then(buf => (buf ? ctx.decodeAudioData(buf.slice(0)) : null))
      .catch(() => null));
  }
  decoded.get(text).then((buffer) => {
    if (!buffer) return;
    if (current) { try { current.stop(); } catch (e) { /* already stopped */ } }
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    src.connect(ctx.destination);
    src.start();
    current = src;
  });
}
